export const ScreenOptions = {
  welcome: {
    headerShown: false,
  },
  login: {
    headerShown: false,
  },
  register: {
    headerShown: false,
  },
  home: {
    headerShown: false,
  },
  verify: {
    title: 'Verify Code',
  },
  car: {
    headerShown: false,
  },
  conversation: {
    headerShown: false,
  },
  notification: {
    headerShown: false,
  },
  personal: {
    headerShown: false,
  },
};

export const API_BASE_URL = 'https://api-vcar-72dg.onrender.com/';
// export const API_BASE_URL = 'http://192.168.1.2:8080/';
export const DEFAULT_AVATAR =
  'https://i.pinimg.com/736x/ee/4e/20/ee4e2079bf453d71c55ddf20fc00d130.jpg';

export enum RENTAL_SYSTEM_MESSAGE {
  LESSEE_SIGNED_CONTRACT,
  NEW_RENTAL_REQUEST,
  RENTAL_REQUEST_APPROVED,
  RENTAL_REQUEST_REJECTED,
}

export enum RENTAL_TYPE {
  RENTAL_CONTRACT,
  RENTAL_REQUEST,
}

export enum API_SYSTEM_MESSAGE {
  WRONG_PASSWORD,
  EMAIL_IN_USE,
  VERIFICATION_CODE_INVALID,
  EMAIL_ALREADY_VERIFIED,
  REFRESH_TOKEN_SUCCESS,
  REFRESH_TOKEN_USED,
  CAR_NOT_FOUND,
  CAR_CREATE_SUCCESS,
  CAR_UPDATE_SUCCESS,
  CAR_DELETE_SUCCESS,
  INVOICE_NOT_FOUND,
  CONTRACT_NOT_FOUND,
  PAYMENT_CREATE_SUCCESS,
  PAYMENT_CALLBACK_SUCCESS,
  PAYMENT_FAILED,
  PAYMENT_NOT_VALID,
  RENTAL_REQUEST_NOT_FOUND,
  USER_NOT_AUTHORIZED,
  USER_AUTHEN_SUCCESS,
  USER_NOT_VERIFIED,
  USER_NOT_FOUND,
  USER_VERIFY_SUCCESS,
  USER_REGISTER_SUCCESS,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_IDENTIFICATION_SUCCESS,
  USER_PHONE_UPDATE_SUCCESS,
  VEHICLE_HANDOVER_NOT_FOUND,
  VEHICLE_HANDOVER_CREATE_SUCCESS,
  VEHICLE_HANDOVER_APPROVE_BY_LESSEE_SUCCESS,
  VEHICLE_HANDOVER_UPDATE_BY_LESSEE_SUCCESS,
  VEHICLE_HANDOVER_APPROVE_BY_LESSOR_SUCCESS,
  SUCCESS,
  RENTAL_REJECT_SUCCESS,
  RENTAL_APPROVE_SUCCESS,
  RENTAL_CREATE_SUCCESS,
  REVIEW_CREATE_SUCCESS,
}

export const provinces = [
  {id: 1, enName: 'Ho Chi Minh', vnName: 'Hồ Chí Minh'},
  {id: 2, enName: 'Hanoi', vnName: 'Hà Nội'},
  {id: 3, enName: 'Da Nang', vnName: 'Đà Nẵng'},
  {id: 4, enName: 'Hai Phong', vnName: 'Hải Phòng'},
  {id: 5, enName: 'Can Tho', vnName: 'Cần Thơ'},
  {id: 6, enName: 'An Giang', vnName: 'An Giang'},
  {id: 7, enName: 'Ba Ria-Vung Tau', vnName: 'Bà Rịa-Vũng Tàu'},
  {id: 8, enName: 'Bac Giang', vnName: 'Bắc Giang'},
  {id: 9, enName: 'Bac Kan', vnName: 'Bắc Kạn'},
  {id: 10, enName: 'Bac Lieu', vnName: 'Bạc Liêu'},
  {id: 11, enName: 'Bac Ninh', vnName: 'Bắc Ninh'},
  {id: 12, enName: 'Ben Tre', vnName: 'Bến Tre'},
  {id: 13, enName: 'Binh Dinh', vnName: 'Bình Định'},
  {id: 14, enName: 'Binh Duong', vnName: 'Bình Dương'},
  {id: 15, enName: 'Binh Phuoc', vnName: 'Bình Phước'},
  {id: 16, enName: 'Binh Thuan', vnName: 'Bình Thuận'},
  {id: 17, enName: 'Ca Mau', vnName: 'Cà Mau'},
  {id: 18, enName: 'Cao Bang', vnName: 'Cao Bằng'},
  {id: 19, enName: 'Dak Lak', vnName: 'Đắk Lắk'},
  {id: 20, enName: 'Dak Nong', vnName: 'Đắk Nông'},
  {id: 21, enName: 'Dien Bien', vnName: 'Điện Biên'},
  {id: 22, enName: 'Dong Nai', vnName: 'Đồng Nai'},
  {id: 23, enName: 'Dong Thap', vnName: 'Đồng Tháp'},
  {id: 24, enName: 'Gia Lai', vnName: 'Gia Lai'},
  {id: 25, enName: 'Ha Giang', vnName: 'Hà Giang'},
  {id: 26, enName: 'Ha Nam', vnName: 'Hà Nam'},
  {id: 27, enName: 'Ha Tinh', vnName: 'Hà Tĩnh'},
  {id: 28, enName: 'Hai Duong', vnName: 'Hải Dương'},
  {id: 29, enName: 'Hau Giang', vnName: 'Hậu Giang'},
  {id: 30, enName: 'Hoa Binh', vnName: 'Hòa Bình'},
  {id: 31, enName: 'Hung Yen', vnName: 'Hưng Yên'},
  {id: 32, enName: 'Khanh Hoa', vnName: 'Khánh Hòa'},
  {id: 33, enName: 'Kien Giang', vnName: 'Kiên Giang'},
  {id: 34, enName: 'Kon Tum', vnName: 'Kon Tum'},
  {id: 35, enName: 'Lai Chau', vnName: 'Lai Châu'},
  {id: 36, enName: 'Lam Dong', vnName: 'Lâm Đồng'},
  {id: 37, enName: 'Lang Son', vnName: 'Lạng Sơn'},
  {id: 38, enName: 'Lao Cai', vnName: 'Lào Cai'},
  {id: 39, enName: 'Long An', vnName: 'Long An'},
  {id: 40, enName: 'Nam Dinh', vnName: 'Nam Định'},
  {id: 41, enName: 'Nghe An', vnName: 'Nghệ An'},
  {id: 42, enName: 'Ninh Binh', vnName: 'Ninh Bình'},
  {id: 43, enName: 'Ninh Thuan', vnName: 'Ninh Thuận'},
  {id: 44, enName: 'Phu Tho', vnName: 'Phú Thọ'},
  {id: 45, enName: 'Phu Yen', vnName: 'Phú Yên'},
  {id: 46, enName: 'Quang Binh', vnName: 'Quảng Bình'},
  {id: 47, enName: 'Quang Nam', vnName: 'Quảng Nam'},
  {id: 48, enName: 'Quang Ngai', vnName: 'Quảng Ngãi'},
  {id: 49, enName: 'Quang Ninh', vnName: 'Quảng Ninh'},
  {id: 50, enName: 'Quang Tri', vnName: 'Quảng Trị'},
  {id: 51, enName: 'Soc Trang', vnName: 'Sóc Trăng'},
  {id: 52, enName: 'Son La', vnName: 'Sơn La'},
  {id: 53, enName: 'Tay Ninh', vnName: 'Tây Ninh'},
  {id: 54, enName: 'Thai Binh', vnName: 'Thái Bình'},
  {id: 55, enName: 'Thai Nguyen', vnName: 'Thái Nguyên'},
  {id: 56, enName: 'Thanh Hoa', vnName: 'Thanh Hóa'},
  {id: 57, enName: 'Thua Thien Hue', vnName: 'Thừa Thiên Huế'},
  {id: 58, enName: 'Tien Giang', vnName: 'Tiền Giang'},
  {id: 59, enName: 'Tra Vinh', vnName: 'Trà Vinh'},
  {id: 60, enName: 'Tuyen Quang', vnName: 'Tuyên Quang'},
  {id: 61, enName: 'Vinh Long', vnName: 'Vĩnh Long'},
  {id: 62, enName: 'Vinh Phuc', vnName: 'Vĩnh Phúc'},
  {id: 63, enName: 'Yen Bai', vnName: 'Yên Bái'},
];
