// [REQUEST]
export const RENT_REQUEST = "RENT_REQUEST";
export const LESSOR_APPROVE_REQUEST = "LESSOR_APPROVE_REQUEST";
export const LESSOR_REJECT_REQUEST = "LESSOR_REJECT_REQUEST";
export const GET_LESSEE_REQUESTS = "GET_LESSEE_REQUESTS";
export const GET_LESSOR_REQUESTS = "GET_LESSOR_REQUESTS";

// [CONTRACT]
export const GET_LESSEE_CONTRACTS = "GET_LESSEE_CONTRACTS";
export const GET_LESSOR_CONTRACTS = "GET_LESSOR_CONTRACTS";
export const GET_CONTRACT_BY_ID = "GET_CONTRACT_BY_ID";
export const LESSEE_APPROVE_CONTRACT = "LESSEE_APPROVE_CONTRACT";

// [Handover]
