export const GET_ME = 'GET_ME';
export const UPDATE_ME = 'UPDATE_ME';
export const FIND_USER_BY_ID = 'FIND_USER_BY_ID';
export const UPDATE_LICENSE = 'UPDATE_LICENSE';
export const UPDATE_CITIZEN_IDENTIFICATION = 'UPDATE_CITIZEN_IDENTIFICATION';
