// [USER]
export const USER_STATISTICS_CONTRACTS = 'LESSOR_STATISTICS_CONTRACTS';
export const USER_STATISTICS_CARS = 'USER_STATISTICS_CARS';

// [ADMIN]
export const ADMIN_STATISTICS_INVOICES = 'ADMIN_STATISTICS_INVOICES';
export const ADMIN_STATISTICS_CONTRACTS = 'ADMIN_STATISTICS_CONTRACTS';
export const ADMIN_STATISTICS_USERS = 'ADMIN_STATISTICS_USERS';
export const ADMIN_STATISTICS_CARS = 'ADMIN_STATISTICS_CARS';
export const ADMIN_STATISTICS_CARS_BY_PROVINCE = 'ADMIN_STATISTICS_CARS_BY_PROVINCE';
export const ADMIN_STATISTICS_RENTAL_VOLUME = 'ADMIN_STATISTICS_RENTAL_VOLUME';